#spring.datasource.url=jdbc:mysql://be9ae91755e0b4:86b5073d@us-cdbr-east-04.cleardb.com/heroku_d941657db80a11c?reconnect=true
spring.datasource.url=jdbc:mysql://localhost:3306/agenda?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
